### ISSUE TITLE
Only loads once

### ISSUE THREAD

**Issue by OusmBlueNinja** [ZetaMap/moreCommands#10]
the plugin only loads onece then i have to delete all of the server files like settings.log and admin-logs

**Comment by ZetaMap** [comment]
it's normal that the plugin loads only once, it does it at server start like all other plugins. To disable the admin-logs you can use the ``alogs off`` command, and for the settings.log i don't have a solution. 
But I don't understand why you want to delete this kind of file

**Comment by ZetaMap** [comment]
@OusmBlueNinja

**Comment by ZetaMap** [comment]
issue pending, i close it...
