### ISSUE TITLE
/effect 84 disconnects all players within range in server

### ISSUE THREAD

**Issue by quantum-brokengrammar** [ZetaMap/moreCommands#14]

**Comment by ZetaMap** [comment]
if crash all players, just disable this effect with command ``effect off 84`` and reboot your server

**Comment by ZetaMap** [comment]
there are lot effect can crash your server, i made a default config to disable problematic effects, use command ``effect default``.

**Comment by ZetaMap** [comment]
default disabled effect list is ["none", "unitSpawn", "unitControl", "unitDespawn", "unitSpirit", "itemTransfer", "pointBeam", "lightning", "unitWreck", "rocketSmoke", "rocketSmokeLarge", "fireSmoke", "melting", "wet", "muddy", "oily", "dropItem", "impactcloud", "unitShieldBreak", "coreLand"]. What is name of effect 84? if is in this list, is probably an wrong effect, so just use the default config

**Comment by ZetaMap** [comment]
issue pending, closing...

**Comment by quantum-brokengrammar** [comment]
dropItem

**Comment by quantum-brokengrammar** [comment]
idk wait ima check

**Comment by quantum-brokengrammar** [comment]
oh its thtere already
