### ISSUE TITLE
Spoofing an admin name is prohibited! (even if not entirely)

### ISSUE THREAD

**Issue by quantum-brokengrammar** [ZetaMap/MoreCommands#17]
I want to disable this feature but how?

**Comment by quantum-brokengrammar** [comment]
How do i remove auto plugin kicking

**Comment by ZetaMap** [comment]
I forgot to create a command for this. Only way for moment is to remove the line in source code and rebuild the plugin

Remove lines 275 at 280 in file src/main/java/manager/BansManager.java

**Comment by quantum-brokengrammar** [comment]
oh ok
