### ISSUE TITLE
Founded bugs

### ISSUE THREAD

**Issue by ZetaMap** [ZetaMap/moreCommands#9]
- ban ip with no reason don't work
- vpnapi.io request change
- TempData.inGodmode exception if player timed out
- Auto pause, pause the game if game over
- plugin don't work in v7

**Comment by quantum-brokengrammar** [comment]
aaaaaaaaaaaaaa

**Comment by quantum-brokengrammar** [comment]
plugin does'nt work in v7 cuz of effect and rainbow command

**Comment by ZetaMap** [comment]
I known , but i'm studient and i don't have much Time to work on the plugin

**Comment by quantum-brokengrammar** [comment]
Ok

**Comment by ZetaMap** [comment]
done, work finished

close issue
